### ISSUE TITLE
FairMQ v1.5.0 no longer uses "ofi-size-hint" parameter

### ISSUE THREAD

**Issue by tntakahashi** [spadi-alliance/nestdaq#43]
FairMQ v1.5.0 no longer uses "ofi-size-hint" parameter. 
The parameter is used in nestdaq/plugins/ParameterConfigPlugins.cxx and nestdaq/plugins/DaqServicePlugin.cxx. 
These files must be fixed.

**Comment by igalashi** [comment]
fixed
